name: zip_to_module

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/zip_to_module.yml'
      - 'Alpine_Chroot_rootfs/**'
      - 'Alpine_Chroot_Extractor/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/zip_to_module.yml'
      - 'Alpine_Chroot_rootfs/**'
      - 'Alpine_Chroot_Extractor/**'
  workflow_call:
